-- apply changes
create table cookie (
  id                            bigint generated by default as identity not null,
  from_id                       bigint not null,
  to_id                         bigint not null,
  reason                        varchar(255),
  created_at                    timestamp not null,
  last_modified_at              timestamp not null,
  created_by_id                 bigint,
  last_modified_by_id           bigint,
  constraint pk_cookie primary key (id)
);

create table users (
  id                            bigint generated by default as identity not null,
  username                      varchar(255) not null,
  created_at                    timestamp not null,
  last_modified_at              timestamp not null,
  created_by_id                 bigint,
  last_modified_by_id           bigint,
  constraint uq_users_username unique (username),
  constraint pk_users primary key (id)
);

-- foreign keys and indices
create index ix_cookie_from_id on cookie (from_id);
alter table cookie add constraint fk_cookie_from_id foreign key (from_id) references users (id) on delete restrict on update restrict;

create index ix_cookie_to_id on cookie (to_id);
alter table cookie add constraint fk_cookie_to_id foreign key (to_id) references users (id) on delete restrict on update restrict;

create index ix_cookie_created_by_id on cookie (created_by_id);
alter table cookie add constraint fk_cookie_created_by_id foreign key (created_by_id) references users (id) on delete restrict on update restrict;

create index ix_cookie_last_modified_by_id on cookie (last_modified_by_id);
alter table cookie add constraint fk_cookie_last_modified_by_id foreign key (last_modified_by_id) references users (id) on delete restrict on update restrict;

create index ix_users_created_by_id on users (created_by_id);
alter table users add constraint fk_users_created_by_id foreign key (created_by_id) references users (id) on delete restrict on update restrict;

create index ix_users_last_modified_by_id on users (last_modified_by_id);
alter table users add constraint fk_users_last_modified_by_id foreign key (last_modified_by_id) references users (id) on delete restrict on update restrict;

